### ISSUE TITLE
Floating IP failing with KeyError

### ISSUE THREAD

**Issue by smacz42** [ansible-collections/community.digitalocean#128] opened 2021-07-15 05:16 UTC
I have simplified my playbook down to one task with hardcoded params:

```yaml
- name: DO VM Setup
  hosts: localhost
  connection: local
  vars_files:
    - ../environment/group_vars/all/all.yml

  tasks:
    - name: Create a new floating IP for this domain if there is not one already
      digital_ocean_floating_ip:
        droplet_id: "254918204"
        state: present
        oauth_token: "{{ do_oauth_token }}"
```

This playbook fails with the following error:

```
MSG:

MODULE FAILURE
See stdout/stderr for the exact error


MODULE_STDERR:

Traceback (most recent call last):
  File "/home/rundeck/.ansible/tmp/ansible-tmp-1626321992.102645-25158-220044443395692/AnsiballZ_digital_ocean_floating_ip.py", line 102, in <module>
    _ansiballz_main()
  File "/home/rundeck/.ansible/tmp/ansible-tmp-1626321992.102645-25158-220044443395692/AnsiballZ_digital_ocean_floating_ip.py", line 94, in _ansiballz_main
    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)
  File "/home/rundeck/.ansible/tmp/ansible-tmp-1626321992.102645-25158-220044443395692/AnsiballZ_digital_ocean_floating_ip.py", line 40, in invoke_module
    runpy.run_module(mod_name='ansible_collections.community.digitalocean.plugins.modules.digital_ocean_floating_ip', init_globals=None, run_name='__main__', alter_sys=True)
  File "/usr/lib/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tmp/ansible_digital_ocean_floating_ip_payload_4fdpcyul/ansible_digital_ocean_floating_ip_payload.zip/ansible_collections/community/digitalocean/plugins/modules/digital_ocean_floating_ip.py", line 311, in <module>
  File "/tmp/ansible_digital_ocean_floating_ip_payload_4fdpcyul/ansible_digital_ocean_floating_ip_payload.zip/ansible_collections/community/digitalocean/plugins/modules/digital_ocean_floating_ip.py", line 307, in main
  File "/tmp/ansible_digital_ocean_floating_ip_payload_4fdpcyul/ansible_digital_ocean_floating_ip_payload.zip/ansible_collections/community/digitalocean/plugins/modules/digital_ocean_floating_ip.py", line 206, in core
  File "/tmp/ansible_digital_ocean_floating_ip_payload_4fdpcyul/ansible_digital_ocean_floating_ip_payload.zip/ansible_collections/community/digitalocean/plugins/modules/digital_ocean_floating_ip.py", line 280, in create_floating_ips
KeyError: 'message'
```

After running into this error, I checked the DO dashboard, and the floating IP is in fact created.

This was in US-East-3 at this time of day. There are no active issues at https://status.digitalocean.com.

```
rundeck@2acb524ea9be:~/5c94c046-61d4-4351-96dc-e253db2fe138-84732$ ansible --version
ansible 2.10.10
  config file = /home/rundeck/5c94c046-61d4-4351-96dc-e253db2fe138-84732/ansible.cfg
  configured module search path = ['/home/rundeck/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0]
```

I exploded the module and printed the:

1. `status_code`: `200`
2. `json_data`:
```
{'floating_ip': {'ip': '45.55.99.174', 'droplet': None, 'region': {'name': 'New York 3', 'slug': 'nyc3', 'features': ['backups', 'ipv6', 'metadata', 'install_agent', 'storage', 'image_transfer'], 'available': True, 'sizes': ['s-1vcpu-1gb', 's-1vcpu-1gb-amd', 's-1vcpu-1gb-intel', 's-1vcpu-2gb', 's-1vcpu-2gb-amd', 's-1vcpu-2gb-intel', 's-2vcpu-2gb', 's-2vcpu-2gb-amd', 's-2vcpu-2gb-intel', 's-2vcpu-4gb', 's-2vcpu-4gb-amd', 's-2vcpu-4gb-intel', 's-4vcpu-8gb', 'c-2', 'c2-2vcpu-4gb', 's-4vcpu-8gb-amd', 's-4vcpu-8gb-intel', 'g-2vcpu-8gb', 'gd-2vcpu-8gb', 's-8vcpu-16gb', 'm-2vcpu-16gb', 'c-4', 'c2-4vcpu-8gb', 's-8vcpu-16gb-amd', 's-8vcpu-16gb-intel', 'm3-2vcpu-16gb', 'g-4vcpu-16gb', 'so-2vcpu-16gb', 'm6-2vcpu-16gb', 'gd-4vcpu-16gb', 'so1_5-2vcpu-16gb', 'm-4vcpu-32gb', 'c-8', 'c2-8vcpu-16gb', 'm3-4vcpu-32gb', 'g-8vcpu-32gb', 'so-4vcpu-32gb', 'm6-4vcpu-32gb', 'gd-8vcpu-32gb', 'so1_5-4vcpu-32gb', 'm-8vcpu-64gb', 'c-16', 'c2-16vcpu-32gb', 'm3-8vcpu-64gb', 'g-16vcpu-64gb', 'so-8vcpu-64gb', 'm6-8vcpu-64gb', 'gd-16vcpu-64gb', 'so1_5-8vcpu-64gb', 'm-16vcpu-128gb', 'c-32', 'c2-32vcpu-64gb', 'm3-16vcpu-128gb', 'm-24vcpu-192gb', 'g-32vcpu-128gb', 'so-16vcpu-128gb', 'm6-16vcpu-128gb', 'gd-32vcpu-128gb', 'm3-24vcpu-192gb', 'g-40vcpu-160gb', 'so1_5-16vcpu-128gb', 'gd-40vcpu-160gb', 'so-24vcpu-192gb', 'm6-24vcpu-192gb', 'so1_5-24vcpu-192gb']}, 'locked': True}, 'links': {}}
```

So it looks like it's erroring out despite returning a `200`. This seems to be because `json_data['floating_ip']['droplet']` is returning `None`. However, it looks like it is getting assigned to the droplet appropriately.

Additionally, when I re-run the playbook, it comes back "OK", with the correct information. Is seems like the API is not returning the droplet info either fast enough, or at all when the floating IP is being created. Therefore, https://github.com/ansible-collections/community.digitalocean/blob/main/plugins/modules/digital_ocean_floating_ip.py#L301 returns false, and continues on to the `else:` statement in https://github.com/ansible-collections/community.digitalocean/blob/main/plugins/modules/digital_ocean_floating_ip.py#L316-L318.

**Comment by smacz42** [comment] 2021-07-15 05:17
P.S. - this was using version 1.8.0 of the collection.

**Comment by tadeboro** [comment] 2021-07-15 06:18
Hello @smacz42. Judging by the information you provided, https://github.com/ansible-collections/community.digitalocean/blob/dd5b3bb7aafec2194b55a34decf525869fc9e1ee/plugins/modules/digital_ocean_floating_ip.py#L314-L318 is where things go wrong. The module expects the DO API to return 202 when the address is created (the [API docs](https://developers.digitalocean.com/documentation/v2/#create-a-new-floating-ip-assigned-to-a-droplet) agree with that assumption), but it looks like that in your case, the API responded with 200.

Is this behavior reproducible? Do you get this failure every time you try to add floating IP to a droplet that does not already have one?

**Comment by smacz42** [comment] 2021-07-15 22:37
Well, last night it failed multiple times on multiple different droplets. Now it seems to be going ok?

I'll try a couple more tests and report back.

FWIW, if you look a couple lines before what you posted, you will also see an `exit_json` call with a `status_code` of `200` condition.

**Comment by tadeboro** [comment] 2021-07-16 06:55
> FWIW, if you look a couple lines before what you posted, you will also see an `exit_json` call with a `status_code` of `200` condition.

Those lines are not problematic (the lines reported by ansible are a bit misleading in this case because the module code is mangled a bit by ansible before being executed). They just check if the droplet we want to give a floating IP to already has one. And judging by your problem description, that part of the code work just fine (this is why rerunning the playbook "fixed" the problem). This is also the reason why I asked whether you only encounter that problem on droplets with no floating IP.

**Comment by smacz42** [comment] 2021-07-16 23:00
Either way, I was able to use this module successfully many times over the past 2 days. So I'm just going to say that there was something odd about the interaction that I was testing with. Whether it was my setup, or DO had a blip at that time, I don't think I'll ever know. But I have not been able to reproduce, so I'll just go ahead and close this out.

**Comment by smacz42** [comment] 2021-07-21 23:45
This has resurfaced and continues to be an issue.

**Comment by mamercad** [comment] 2021-07-22 21:51
I've reproduced this just now.

**Comment by mamercad** [comment] 2021-07-22 22:04
I'm asking around internally...

**Comment by mamercad** [comment] 2021-07-22 22:08
I have internal confirmation of a bug at this point!

**Comment by mamercad** [comment] 2021-07-22 23:21
The internal bug is open, but, it *may* be fixed temporarily. I'm watching the bug and will update/close this one along with it.

**Comment by mamercad** [comment] 2021-07-27 18:07
@smacz42 I've gotten internal confirmation that this should be resolved, have you been able to reproduce it lately?

**Comment by smacz42** [comment] 2021-07-28 03:09
Nope, haven't been able to reproduce lately!

**Closed** 2021-07-28 13:05 UTC
Labels: bug, internal_bug
